/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'surface': '#fdf9f0',
        'surface-dim': '#dddad1',
        'surface-bright': '#fdf9f0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3ea',
        'surface-container': '#f1eee5',
        'surface-container-high': '#ece8df',
        'surface-container-highest': '#e6e2d9',
        'on-surface': '#1c1c16',
        'on-surface-variant': '#4d4639',
        'inverse-surface': '#31302b',
        'inverse-on-surface': '#f4f0e7',
        'outline': '#7f7667',
        'outline-variant': '#d0c5b4',
        'surface-tint': '#745b1b',
        'primary': '#745b1b',
        'on-primary': '#ffffff',
        'primary-container': '#c9a961',
        'on-primary-container': '#533d00',
        'inverse-primary': '#e4c278',
        'secondary': '#5a5f68',
        'on-secondary': '#ffffff',
        'secondary-container': '#dee2ee',
        'on-secondary-container': '#60656e',
        'tertiary': '#625e58',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b2aca6',
        'on-tertiary-container': '#44403b',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdf9b',
        'primary-fixed-dim': '#e4c278',
        'on-primary-fixed': '#251a00',
        'background': '#fdf9f0',
        'on-background': '#1c1c16',
        'surface-variant': '#e6e2d9',
      },
      spacing: {
        'gutter': '24px',
        'stack-gap': '16px',
        'container-margin': '48px',
        'section-padding': '80px',
        'card-padding': '32px',
      },
      fontFamily: {
        'newsreader': ['Newsreader', 'serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
      },
    },
  },
  corePlugins: {
    preflight: true,
  },
  plugins: [],
};
